status = ["ci/circleci: build", "ci/circleci: test", "ci/circleci: e2e"]
pr_status = ["UI Tests", "Vercel Preview Comments"]
delete_merged_branches = true
use_squash_merge = true
cut_body_after = "### Implementation details. How do you make this change?"
required_approvals = 1
update_base_for_deletes = true
